import { organizationalExperience } from "@/types";

export const organizationalExperienceList: organizationalExperience[] = [
  {
    jobDesk: "Secretary 1",
    companyName: "KBMDSI FILKOM UB 2024/2025",
    years: "Feb 2024 - Present",
    jobDescription: "Managed the administrative needs and maintained the organization's inventory ;Maintained and preserved organizational documents, records, and archives ;Managed the submission of work program administration documents, including proposals, accountability reports, final activity reports, letters, etc. ",
    companyLogo: "/assets/images/kbmdsiub.png", 
  },
  {
    jobDesk: "Staff of Security Division",
    companyName: "POROS Organization Of Open Source FILKOM UB",
    years: "Mar 2023 - Present",
    jobDescription: "Learned how to secure code, implement security as code, and secure systems ;Enhanced security problem-solving skills through participating in Capture the Flag (CTF) challenges and collaborating with a team",
    companyLogo: "/assets/images/porosfilkom.png", 
  },
  {
    jobDesk: "Secretary 2",
    companyName: "KBMDSI FILKOM UB 2023/2024",
    years: "Mar 2023 - Feb 2024",
    jobDescription: "Managed the administrative needs and maintained the organization's inventory ;Maintained and preserved organizational documents, records, and archives ;Successfully managed the submission of over 100+ work program administration documents, including proposals, accountability reports, final activity reports, letters, etc.",
    companyLogo: "/assets/images/kbmdsiub.png", 
  },
  {
    jobDesk: "Problem Setter CTF",
    companyName: "CODEX 2023",
    years: "Oct 2023 - Nov 2023",
    jobDescription: "Developed and reviewed CTF challenge ;Collaborated with other problem setters to ensure the quality of the challenge",
    companyLogo: "/assets/images/codex.png", 
  },
  {
    jobDesk: "Staff of Event Division",
    companyName: "COSMOS 2023",
    years: "Aug 2023 - Nov 2023",
    jobDescription: "Actively involved in developing event concepts and themes ;Responsible for designing every event detail",
    companyLogo: "/assets/images/cosmosporos.png", 
  },
  {
    jobDesk: "Staff of IT Division",
    companyName: "GEMASTIK XVI 2023",
    years: "Sep 2023",
    jobDescription: "Managed the technology infrastructure required during events, including networks, servers, and other hardware, ensuring seamless operation ;Ensured the smooth functionality and connectivity of all technology devices, guarantee uninterrupted operations ;Provided technical support to all involved teams, troubleshooting technical issues and delivering real-time solutions",
    companyLogo: "/assets/images/gemastik.png", 
  },
  {
    jobDesk: "Staff of Event Division",
    companyName: "PEMILWA KBMDSI 2022",
    years: "Nov 2022 - Jan 2023",
    jobDescription: "Coordinated and organized the student representative election event ;Responsible for the planning, execution, and evaluation of the student representative election event",
    companyLogo: "/assets/images/pemilwakbmdsi.png", 
  },
  {
    jobDesk: "Staff of Organizational Quality Assurance Center",
    companyName: "KBMPTI FILKOM UB 2022/2023",
    years: "Feb 2022 - Jan 2023",
    jobDescription: "Fostered and enhanced the quality and quantity of human resources within the organization ;Conducted performance monitoring for members of the organization",
    companyLogo: "/assets/images/kbmptiub.png", 
  },
  {
    jobDesk: "Staff of Public Relations",
    companyName: "HOLOGY 5.0",
    years: "Jun 2022 - Nov 2022",
    jobDescription: "Communicated with the public and disseminated information about the event ;Responsible for the maintenance of events social media ;Contacted and assisted speakers in the preparation and execution of the event",
    companyLogo: "/assets/images/hology.png", 
  },
  {
    jobDesk: "Head of Event Division",
    companyName: "EDUACTION 3.0",
    years: "Jun 2022 - Nov 2022",
    jobDescription: "Led a team of 8 staff to coordinate and organize the event ;Responsible for the planning, execution, and evaluation of the event ;Successfully organized an event with over 50 participants",
    companyLogo: "/assets/images/eduaction.png", 
  },
  {
    jobDesk: "Secretary",
    companyName: "GENESIS 8.0",
    years: "Jun 2022 - Nov 2022",
    jobDescription: "Drafted every proposal, accountability report, and all administrative matters ;Responsible for storing and maintaining committee documents, records, and archives ;Recorded and distributed meeting minutes and notes, and followed up on necessary actions",
    companyLogo: "/assets/images/genesis.png", 
  },
  {
    jobDesk: "Secretary Young Staff",
    companyName: "KBMPTI FILKOM UB 2021/2022",
    years: "Oct 2021 - Jan 2022",
    jobDescription: "Learned and assisted in the workflow as a secretary at the organization ;Supported administrative activities and secretary tasks in the organization",
    companyLogo: "/assets/images/kbmptiub.png", 
  },
];